### ISSUE TITLE
OutOfBoundsDatetime error when reading dbf

### ISSUE THREAD

**Issue by martinfleis** [geopandas/pyogrio#230] opened 2023-03-19 09:41 UTC
Hey, I tried to read a dbf file (no geometry) with pyogrio and got `OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 9999-09-09 00:00:00`. 

Fiona is able to read the file with no issue. 

The datetime in the file is 9999. It is an end date of data validity, so I guess that the author tried to indicate that it does not have a limit... So the error is correct but it prevents me from reading the data. Fiona doesn't complain and returns `'9999-09-09'` strings. Can we maybe capture issue like this and fall back to string or `NaT` with a warning when it happens? Not entirely sure how since this is coming from pandas and `pyogrio.raw.read` has no issue with that.

The file (from the Czech Statistical Office, so an official source) is attached (zipped).

[CIS55.dbf.zip](https://github.com/geopandas/pyogrio/files/11010611/CIS55.dbf.zip)

```py
data  = pyogrio.read_dataframe("CIS55.dbf")
```

```py
---------------------------------------------------------------------------
OutOfBoundsDatetime                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 data  = pyogrio.read_dataframe("[/Users/martin/Downloads/CIS55.dbf](https://untitled+.vscode-resource.vscode-cdn.net/Users/martin/Downloads/CIS55.dbf)")

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pyogrio/geopandas.py:161](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pyogrio/geopandas.py:161), in read_dataframe(path_or_buffer, layer, encoding, columns, read_geometry, force_2d, skip_features, max_features, where, bbox, fids, sql, sql_dialect, fid_as_index)
    158 else:
    159     index = None
--> 161 df = pd.DataFrame(data, columns=columns, index=index)
    163 if geometry is None or not read_geometry:
    164     return df

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/frame.py:663](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/frame.py:663), in DataFrame.__init__(self, data, index, columns, dtype, copy)
    657     mgr = self._init_mgr(
    658         data, axes={"index": index, "columns": columns}, dtype=dtype, copy=copy
    659     )
    661 elif isinstance(data, dict):
    662     # GH#38939 de facto copy defaults to False only in non-dict cases
--> 663     mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
    664 elif isinstance(data, ma.MaskedArray):
    665     import numpy.ma.mrecords as mrecords

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/internals/construction.py:493](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/internals/construction.py:493), in dict_to_mgr(data, index, columns, dtype, typ, copy)
    489     else:
    490         # dtype check to exclude e.g. range objects, scalars
    491         arrays = [x.copy() if hasattr(x, "dtype") else x for x in arrays]
--> 493 return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/internals/construction.py:123](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/internals/construction.py:123), in arrays_to_mgr(arrays, columns, index, dtype, verify_integrity, typ, consolidate)
    120         index = ensure_index(index)
    122     # don't force copy because getting jammed in an ndarray anyway
--> 123     arrays = _homogenize(arrays, index, dtype)
    124     # _homogenize ensures
    125     #  - all(len(x) == len(index) for x in arrays)
    126     #  - all(x.ndim == 1 for x in arrays)
   (...)
    129 
    130 else:
    131     index = ensure_index(index)

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/internals/construction.py:617](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/internals/construction.py:617), in _homogenize(data, index, dtype)
    614             val = dict(val)
    615         val = lib.fast_multiget(val, oindex._values, default=np.nan)
--> 617     val = sanitize_array(
    618         val, index, dtype=dtype, copy=False, raise_cast_failure=False
    619     )
    620     com.require_length_match(val, index)
    622 homogenized.append(val)

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/construction.py:597](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/construction.py:597), in sanitize_array(data, index, dtype, copy, raise_cast_failure, allow_2d)
    594             subarr = np.array(data, copy=copy)
    595     else:
    596         # we will try to copy by-definition here
--> 597         subarr = _try_cast(data, dtype, copy, raise_cast_failure)
    599 elif isinstance(data, ABCExtensionArray):
    600     # it is already ensured above this is not a PandasArray
    601     subarr = data

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/construction.py:775](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/construction.py:775), in _try_cast(arr, dtype, copy, raise_cast_failure)
    773 arr = cast(np.ndarray, arr)
    774 if arr.dtype != object:
--> 775     return sanitize_to_nanoseconds(arr, copy=copy)
    777 out = maybe_infer_to_datetimelike(arr)
    778 if out is arr and copy:

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1428](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1428), in sanitize_to_nanoseconds(values, copy)
   1426 dtype = values.dtype
   1427 if dtype.kind == "M" and dtype != DT64NS_DTYPE:
-> 1428     values = astype_overflowsafe(values, dtype=DT64NS_DTYPE)
   1430 elif dtype.kind == "m" and dtype != TD64NS_DTYPE:
   1431     values = astype_overflowsafe(values, dtype=TD64NS_DTYPE)

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/_libs/tslibs/np_datetime.pyx:288](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/_libs/tslibs/np_datetime.pyx:288), in pandas._libs.tslibs.np_datetime.astype_overflowsafe()

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/_libs/tslibs/np_datetime.pyx:379](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/_libs/tslibs/np_datetime.pyx:379), in pandas._libs.tslibs.np_datetime.astype_overflowsafe()

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/_libs/tslibs/np_datetime.pyx:368](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/_libs/tslibs/np_datetime.pyx:368), in pandas._libs.tslibs.np_datetime.astype_overflowsafe()

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/_libs/tslibs/np_datetime.pyx:212](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/_libs/tslibs/np_datetime.pyx:212), in pandas._libs.tslibs.np_datetime.check_dts_bounds()

OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 9999-09-09 00:00:00---------------------------------------------------------------------------
OutOfBoundsDatetime                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 data  = pyogrio.read_dataframe("[/Users/martin/Downloads/CIS55.dbf](https://untitled+.vscode-resource.vscode-cdn.net/Users/martin/Downloads/CIS55.dbf)")

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pyogrio/geopandas.py:161](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pyogrio/geopandas.py:161), in read_dataframe(path_or_buffer, layer, encoding, columns, read_geometry, force_2d, skip_features, max_features, where, bbox, fids, sql, sql_dialect, fid_as_index)
    158 else:
    159     index = None
--> 161 df = pd.DataFrame(data, columns=columns, index=index)
    163 if geometry is None or not read_geometry:
    164     return df

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/frame.py:663](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/frame.py:663), in DataFrame.__init__(self, data, index, columns, dtype, copy)
    657     mgr = self._init_mgr(
    658         data, axes={"index": index, "columns": columns}, dtype=dtype, copy=copy
    659     )
    661 elif isinstance(data, dict):
    662     # GH#38939 de facto copy defaults to False only in non-dict cases
--> 663     mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
    664 elif isinstance(data, ma.MaskedArray):
    665     import numpy.ma.mrecords as mrecords

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/internals/construction.py:493](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/internals/construction.py:493), in dict_to_mgr(data, index, columns, dtype, typ, copy)
    489     else:
    490         # dtype check to exclude e.g. range objects, scalars
    491         arrays = [x.copy() if hasattr(x, "dtype") else x for x in arrays]
--> 493 return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/internals/construction.py:123](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/internals/construction.py:123), in arrays_to_mgr(arrays, columns, index, dtype, verify_integrity, typ, consolidate)
    120         index = ensure_index(index)
    122     # don't force copy because getting jammed in an ndarray anyway
--> 123     arrays = _homogenize(arrays, index, dtype)
    124     # _homogenize ensures
    125     #  - all(len(x) == len(index) for x in arrays)
    126     #  - all(x.ndim == 1 for x in arrays)
   (...)
    129 
    130 else:
    131     index = ensure_index(index)

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/internals/construction.py:617](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/internals/construction.py:617), in _homogenize(data, index, dtype)
    614             val = dict(val)
    615         val = lib.fast_multiget(val, oindex._values, default=np.nan)
--> 617     val = sanitize_array(
    618         val, index, dtype=dtype, copy=False, raise_cast_failure=False
    619     )
    620     com.require_length_match(val, index)
    622 homogenized.append(val)

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/construction.py:597](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/construction.py:597), in sanitize_array(data, index, dtype, copy, raise_cast_failure, allow_2d)
    594             subarr = np.array(data, copy=copy)
    595     else:
    596         # we will try to copy by-definition here
--> 597         subarr = _try_cast(data, dtype, copy, raise_cast_failure)
    599 elif isinstance(data, ABCExtensionArray):
    600     # it is already ensured above this is not a PandasArray
    601     subarr = data

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/construction.py:775](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/construction.py:775), in _try_cast(arr, dtype, copy, raise_cast_failure)
    773 arr = cast(np.ndarray, arr)
    774 if arr.dtype != object:
--> 775     return sanitize_to_nanoseconds(arr, copy=copy)
    777 out = maybe_infer_to_datetimelike(arr)
    778 if out is arr and copy:

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1428](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:1428), in sanitize_to_nanoseconds(values, copy)
   1426 dtype = values.dtype
   1427 if dtype.kind == "M" and dtype != DT64NS_DTYPE:
-> 1428     values = astype_overflowsafe(values, dtype=DT64NS_DTYPE)
   1430 elif dtype.kind == "m" and dtype != TD64NS_DTYPE:
   1431     values = astype_overflowsafe(values, dtype=TD64NS_DTYPE)

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/_libs/tslibs/np_datetime.pyx:288](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/_libs/tslibs/np_datetime.pyx:288), in pandas._libs.tslibs.np_datetime.astype_overflowsafe()

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/_libs/tslibs/np_datetime.pyx:379](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/_libs/tslibs/np_datetime.pyx:379), in pandas._libs.tslibs.np_datetime.astype_overflowsafe()

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/_libs/tslibs/np_datetime.pyx:368](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/_libs/tslibs/np_datetime.pyx:368), in pandas._libs.tslibs.np_datetime.astype_overflowsafe()

File [~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/_libs/tslibs/np_datetime.pyx:212](https://untitled+.vscode-resource.vscode-cdn.net/~/mambaforge/envs/stable/lib/python3.10/site-packages/pandas/_libs/tslibs/np_datetime.pyx:212), in pandas._libs.tslibs.np_datetime.check_dts_bounds()

OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 9999-09-09 00:00:00
```

**Comment by jorisvandenbossche** [comment] 2023-03-19 13:30
Yeah, this is a known issue, going to close it as duplicate of https://github.com/geopandas/pyogrio/issues/142

BTW, we might not need to do anything since pandas will start to support non-nanosecond data. Reading the file you linked in an env with pandas 2.0 rc, I see:

```
In [29]: data  = pyogrio.read_dataframe("../Downloads/CIS55.dbf.zip")

In [30]: data
Out[30]: 
    KODCIS     KOD                    TEXT    PLATIOD  NEPLATIPO  POCADR_SO  POCBUDBYT_  POCBUDKRUB  PBUDCP_SO  POCBYT_SO  POCBYTOB_S  POCOBYEV_S  POCOBYSL01  POCOBYOSL1  POCOBYSL11  VYMERA_SO
0     0055  101036  Statistickì obvod 0232 2001-03-01 9999-09-09          6           0           0        4.0          0           0           0           0         2.0         NaN      20185
1     0055  101923  Statistickì obvod 0233 2001-03-01 9999-09-09          0           0           0        NaN          0           0           0           0         NaN         NaN       3063
2     0055  102318  Statistickì obvod 0336 2001-03-01 9999-09-09         17          11           0       15.0        146         126         284         296       249.0       254.0       9736
3     0055  102326  Statistickì obvod 0337 2001-03-01 9999-09-09         13          10           0       10.0        132         115         273         254       225.0       245.0       8458
4     0055  102334  Statistickì obvod 0338 2001-03-01 9999-09-09         14           9           0       10.0        167         155         304         359       277.0       279.0      11071
..     ...     ...                     ...        ...        ...        ...         ...         ...        ...        ...         ...         ...         ...         ...         ...        ...
263   0055  156493  Statistickì obvod 3970 2001-03-01 9999-09-09          8           8           0        8.0         98          90         129         180       141.0       136.0       8587
264   0055  156507  Statistickì obvod 3971 2001-03-01 9999-09-09          7           7           0        7.0        116         111         244         259       229.0       233.0       6015
265   0055  156515  Statistickì obvod 3972 2001-03-01 9999-09-09          9           6           0        7.0        123         118         179         202       181.0       172.0       6475
266   0055  159964  Statistickì obvod 3966 2001-03-01 9999-09-09         11           2           0        9.0          3           2           1           4         2.0         1.0     143399
267   0055  160202  Statistickì obvod 3967 2001-03-01 9999-09-09         31           0           0       31.0          1           1           5           9        43.0         9.0     177662

[268 rows x 16 columns]

In [31]: data.dtypes
Out[31]: 
KODCIS               object
KOD                  object
TEXT                 object
PLATIOD       datetime64[s]
NEPLATIPO     datetime64[s]
POCADR_SO             int64
POCBUDBYT_            int64
POCBUDKRUB            int64
PBUDCP_SO           float64
POCBYT_SO             int64
POCBYTOB_S            int64
POCOBYEV_S            int64
POCOBYSL01            int64
POCOBYOSL1          float64
POCOBYSL11          float64
VYMERA_SO             int64
dtype: object
```

But let's continue that conversation at https://github.com/geopandas/pyogrio/issues/142

**Closed by jorisvandenbossche** 2023-03-19 13:30 UTC
