### ISSUE TITLE
Call for action: test the new wheels

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/pyogrio#112] opened 2022-06-02 15:19 UTC
We have been working on setting up a new infrastructure for building wheels based on cibuildwheel and vcpkg (https://github.com/geopandas/pyogrio/issues/48, https://github.com/geopandas/pyogrio/pull/49, https://github.com/geopandas/pyogrio/issues/54 and others), *including wheels for windows!* `pyogrio` 0.4.0a1 has now been released with wheels for MacOS, Linux, Windows on PyPI (x86_64 architectures only, sorry!). 

It would be very welcome to test those wheels! You can do this by installing the prerelease with pip:

```
pip install --pre pyogrio
```

(includes GDAL 3.4.2 in the wheels)

and then test with reading a file of your own:

```
import pyogrio
pyogrio.read_dataframe("path/to/file")
```

or by running the tests of the installed package, for which you need some extra dependencies:

```
pip install pytest pandas pyproj shapely
pip install --no-deps geopandas
```

```
pytest --pyargs pyogrio
```

If you have a chance to test this version, let us know if you run into issues with installation or `read_dataframe()` / `write_dataframe()`. 
Any feedback (also positive, that it is working for you on your system) is very welcome.

**Comment by mborus** [comment] 2022-06-02 15:53
Tried on Windows 10, Python 3.10.2 64bit, fresh venv with pip updated & pytest installed afterwards

Then "pip install --pre pyogrio"

"pytest --pyargs pyogrio" failed ("message pandas not installed")



Installing geopandas failed
gpt) C:\temp>python -m pip install geopandas
Collecting geopandas
  Using cached geopandas-0.10.2-py2.py3-none-any.whl (1.0 MB)
Collecting fiona>=1.8
  Downloading Fiona-1.8.21.tar.gz (1.0 MB)
     ---------------------------------------- 1.0/1.0 MB 9.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by mborus** [comment] 2022-06-02 15:56
Part 2: Then pip installed pandas and tried "pip install --pre pyogrio" again.

Failed: See attached full output.

=========================== short test summary info ===========================
FAILED gpt/lib/site-packages/pyogrio/tests/test_path.py::test_vsi_handling_read_functions
FAILED gpt/lib/site-packages/pyogrio/tests/test_path.py::test_path_absolute
FAILED gpt/lib/site-packages/pyogrio/tests/test_path.py::test_path_relative
FAILED gpt/lib/site-packages/pyogrio/tests/test_path.py::test_uri_local_file
FAILED gpt/lib/site-packages/pyogrio/tests/test_path.py::test_zip_path - Impo...
FAILED gpt/lib/site-packages/pyogrio/tests/test_path.py::test_detect_zip_path
FAILED gpt/lib/site-packages/pyogrio/tests/test_path.py::test_url - ImportErr...
FAILED gpt/lib/site-packages/pyogrio/tests/test_path.py::test_url_with_zip - ...
FAILED gpt/lib/site-packages/pyogrio/tests/test_path.py::test_uri_s3 - Import...
FAILED gpt/lib/site-packages/pyogrio/tests/test_raw_io.py::test_read_autodetect_driver[.fgb]
FAILED gpt/lib/site-packages/pyogrio/tests/test_raw_io.py::test_read_autodetect_driver[.geojson]
FAILED gpt/lib/site-packages/pyogrio/tests/test_raw_io.py::test_read_autodetect_driver[.geojsonl]
FAILED gpt/lib/site-packages/pyogrio/tests/test_raw_io.py::test_read_autodetect_driver[.geojsons]
FAILED gpt/lib/site-packages/pyogrio/tests/test_raw_io.py::test_read_autodetect_driver[.gpkg]
FAILED gpt/lib/site-packages/pyogrio/tests/test_raw_io.py::test_read_autodetect_driver[.json]
=========== 15 failed, 80 passed, 150 skipped, 3 warnings in 4.61s ============

[output.txt](https://github.com/geopandas/pyogrio/files/8825502/output.txt)

If you provide a test dataframe to import, I could try if it would import.

**Comment by mborus** [comment] 2022-06-02 16:05
OK, tried this (Windows10, 64bit, Python 3.10.2, fresh venv)

python -m pip install pip -U
pip install --pre pyogrio
pip install pytest pandas pyproj shapely
pip install --no-deps geopandas

Works with only some warnings - output attached.

[output2.txt](https://github.com/geopandas/pyogrio/files/8825630/output2.txt)

Happy to test reading a dataframe if you provide a link to an example file to read

**Comment by dtjunkie** [comment] 2022-06-11 13:17
Followed all the instructions. However, when it comes to the pytest --pyargs pyogrio, it returns an import error which says that the GDAL DLL could not be found.  It must be on the system PATH. What could have gone wrong?

![error](https://user-images.githubusercontent.com/90781857/173189605-15ecd1e3-a65e-4487-a1ee-bb041e7349e7.png)

**Comment by brendan-ward** [comment] 2022-06-11 13:42
Thank you @dtjunkie ; I think this is exactly the case I was running into trying to get Windows-specific tests to run correctly on CI before we moved the Windows build to use VCPKG.  However, those have all been working since using VCPKG.

Could you please try these lines from our Windows CI wheel test?

```
python -c "import pyogrio; print(f'GDAL version: {pyogrio.__gdal_version__}\nGEOS version: {pyogrio.__gdal_geos_version__}')"
python -m pytest --pyargs pyogrio.tests -v
```

I _think_ we're bumping into an issue with not correctly resolving the GDAL DLL when running pytest directly.

**Comment by dtjunkie** [comment] 2022-06-11 14:00
Sure, no problem. I'll get back to you with the result.

**Comment by dtjunkie** [comment] 2022-06-11 14:11
I've already try those lines. The first line returns the same error. Furthermore, the second line returns an error message stating that a module or package was not found.
![error_2](https://user-images.githubusercontent.com/90781857/173191380-c16ce937-5d8e-4186-adab-02f6b5efa529.png)

**Comment by brendan-ward** [comment] 2022-06-11 14:21
@dtjunkie thanks for further testing!  Your attempts are valuable, I don't think any of the core devs here have a Windows machine to easily test on, so we're reliant on our Windows CI tests, which don't appear representative in this case.

What version of Windows are you using?

I see that our CI tests are run using Bash on Windows (rather than Powershell / Cmd)?  Is that something you can test if you didn't already so so above?  (I don't know how to run Bash vs Powershell / Cmd, only that it is available as an option on our CI)

I see that you are using a Conda-based environment - is this a clean environment just for pyogrio, or do you have other things installed?  Can you share results of `conda list`?

**Comment by dtjunkie** [comment] 2022-06-11 14:47
I'll be checking on it tomorrow. It's already late evening here in Manila and time for me to take a rest.

**Comment by dtjunkie** [comment] 2022-06-12 05:57
I'm currently using Windows 11 v. 21H2 OS Build 22000.708

**Comment by dtjunkie** [comment] 2022-06-12 07:36
Hi! I tried repeat the steps above using the new conda environment that I created just now. Here's the result when the final step was done.

![pyogrio](https://user-images.githubusercontent.com/90781857/173222518-122be149-1c5d-4d71-9a93-df8e49d60209.png)

**Comment by dtjunkie** [comment] 2022-06-12 07:51
Tried importing and accessing the file using pyogrio and it worked

![pyogrio](https://user-images.githubusercontent.com/90781857/173222989-1e79e204-0778-4628-a44d-05107a19fc17.png)

My question though is whether geopandas can't be used for the time being?

**Comment by brendan-ward** [comment] 2022-06-12 13:57
@dtjunkie Thank you for further testing and reporting back!  It looks like everything worked properly in a clean conda environment, but not in one that already had a bunch of other things installed.  That might give us something to test further with in order to nail down the issue.

> My question though is whether geopandas can't be used for the time being?

I don't know what you mean, can you clarify.  You can certainly use GeoPandas > 0.10 with Pyogrio.  It looks like both the last tests and your manual example worked properly; are you seeing a problem?

**Comment by dtjunkie** [comment] 2022-06-12 14:52
I tried using geopandas (gpd) along with pyogrio but when I tried to use the gpd's read_file function it returns an error stating that the function requires the fiona package which is absent in the --no-deped version of geopandas. Did I do something wrong?

![gpd_error](https://user-images.githubusercontent.com/90781857/173238971-e9cc69a4-ce8e-47fd-a803-cbc36abbf536.png)

**Comment by dtjunkie** [comment] 2022-06-13 09:49
I downloaded the following versions of GDAL and Fiona from this website: https://www.lfd.uci.edu/~gohlke/pythonlibs/

GDAL-3.4.3-cp310-cp310-win_amd64.whl
Fiona-1.8.21-cp310-cp310-win_amd64.whl

When I tested the geopandas' read_file function, it finally worked.

![geopandas_error2](https://user-images.githubusercontent.com/90781857/173327621-cbef383a-50d0-4094-9e39-7b9785b5c3ca.png)

**Comment by ljwolf** [comment] 2022-06-20 17:40
I was also able to get this running today using a fresh miniconda on windows:

```
conda create -n testing
conda activate testing
conda install -c conda-forge pip
pip install --pre pyogrio
pip install pytest pandas pyproj shapely
pip install --no-deps geopandas

pytest --pyargs pyogrio
python -c "import pyogrio, geopandas; print(pyogrio.read_dataframe(geopandas.datasets.get_path('nybb')))"
```
As noted above, geopandas 0.10 won't read files without fiona, but pyogrio worked just fine with this!

**Comment by jorisvandenbossche** [comment] 2022-06-20 18:19
@ljwolf thanks a lot for testing! 
One more thing, could you test doing a `conda install jpeg libcurl libiconv libpng libtiff libwebp libxml2 zlib zstd ` in that environment, and then run the test of pyogrio again? (that might somewhat mimick the environment above in which case the wheel didn't correctly load its bundled GDAL library)

**Comment by ljwolf** [comment] 2022-06-20 18:52
Yep, just did. I still get 254 passes, 12 skips, and 23 warnings, and can read the file fine. 

```
(testing) C:\Users\Levi John Wolf>conda list
# packages in environment at C:\Users\Levi John Wolf\miniconda3\envs\testing:
#
# Name                    Version                   Build  Channel
atomicwrites              1.4.0                    pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
bzip2                     1.0.8                he774522_0
ca-certificates           2022.4.26            haa95532_0
certifi                   2022.5.18.1     py310haa95532_0
colorama                  0.4.5                    pypi_0    pypi
geopandas                 0.10.2                   pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
jpeg                      9e                   h2bbff1b_0
libcurl                   7.82.0               h86230a5_0
libffi                    3.4.2                hd77b12b_4
libiconv                  1.16                 h2bbff1b_2
libpng                    1.6.37               h2a8f88b_0
libssh2                   1.10.0               hcd4344a_0
libtiff                   4.2.0                he0120a3_1
libxml2                   2.9.14               h0ad7f3c_0
lz4-c                     1.9.3                h2bbff1b_1
numpy                     1.23.0rc3                pypi_0    pypi
openssl                   1.1.1o               h2bbff1b_0
packaging                 21.3                     pypi_0    pypi
pandas                    1.4.2                    pypi_0    pypi
pip                       22.1.2                   pypi_0    pypi
pluggy                    1.0.0                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pyogrio                   0.4.0b1                  pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyproj                    3.3.1                    pypi_0    pypi
pytest                    7.1.2                    pypi_0    pypi
python                    3.10.4               hbb2ffb3_0
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2022.1                   pypi_0    pypi
setuptools                61.2.0          py310haa95532_0
shapely                   1.8.2                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.38.3               h2bbff1b_0
tk                        8.6.12               h2bbff1b_0
tomli                     2.0.1                    pypi_0    pypi
tzdata                    2022a                hda174b7_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2             py310haa95532_2
xz                        5.2.5                h8cc25b3_1
zlib                      1.2.12               h8cc25b3_2
zstd                      1.5.2                h19a0ad4_0
```

**Comment by jorisvandenbossche** [comment] 2022-06-20 18:57
OK, thanks for testing. Then there was still something else going wrong in @dtjunkie's env, but it is good to know that having those packages that are bundled in the wheel also installed normally doesn't generally mess up the wheel.

**Comment by m-richards** [comment] 2022-07-02 07:49
I've also managed to install and test the wheels successfully on a couple of windows computers using pip inside a virtualenv with no issues.

**Comment by sutanAE** [comment] 2022-07-06 10:18
- tried on windows 10 in an virtual env, 
- tried on conda environment too
- upgraded my pip and 
- computer is x64


it yielded these errors.

```
$ python -m venv "test_geopandas_wheel"
$ . test_geopandas_wheel/Scripts/activate
$ python -V
Python 3.7.0
$ pip -V
pip 22.1.2
$ pip install --pre pyogrio
Collecting pyogrio
  Using cached pyogrio-0.3.0.tar.gz (322 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error


 Getting requirements to build wheel did not run successfully.
  exit code: 1

  [24 lines of output]
  Traceback (most recent call last):
    File ".\test_geopandas_wheel\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File ".\test_geopandas_wheel\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File ".\test_geopandas_wheel\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\<USERS>~1\AppData\Local\Temp\pip-build-env-6_g226y_\overlay\Lib\site-packages\setuptools\build_meta.py", line 178, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "C:\Users\<USERS>~1\AppData\Local\Temp\pip-build-env-6_g226y_\overlay\Lib\site-packages\setuptools\build_meta.py", line 159, in _get_build_requires
      self.run_setup()
    File "C:\Users\<USERS>~1\AppData\Local\Temp\pip-build-env-6_g226y_\overlay\Lib\site-packages\setuptools\build_meta.py", line 282, in run_setup
      self).run_setup(setup_script=setup_script)
    File "C:\Users\<USERS>~1\AppData\Local\Temp\pip-build-env-6_g226y_\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 131, in <module>
      compiler_directives={"language_level": "3"},
    File "C:\Users\<USERS>~1\AppData\Local\Temp\pip-build-env-6_g226y_\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 986, in cythonize
      aliases=aliases)
    File "C:\Users\<USERS>~1\AppData\Local\Temp\pip-build-env-6_g226y_\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 821, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "C:\Users\<USERS>~1\AppData\Local\Temp\pip-build-env-6_g226y_\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 116, in nonempty
      raise ValueError(error_msg)
  ValueError: 'pyogrio/_err.pyx' doesn't match any files
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(test_geopandas_wheel)

```

**Comment by brendan-ward** [comment] 2022-07-06 12:25
@sutanAE sorry for the issues!  Something is clearly not right with that installation call, as it is using the 0.3.0 source distribution instead of the currently available 0.4.0 wheels, and it is failing because it is trying to build 0.3.0 from source (not sure why it is using the 0.3.0 source distribution rather than 0.4.0, maybe a caching issue on your end?).  

I do see that you are using Python 3.7, which is older than our oldest [officially supported version](https://github.com/geopandas/pyogrio#requirements) of 3.8.  We don't have pre-built wheel files available for older versions of Python.  Can you please try again within a Python 3.8+ environment?

Also, now that 0.4.0 is officially released, you should not need to use the `--pre` flag; you should now be able to use `pip install pyogrio` to get it.  Alternatively, `pip install pyogrio==0.4.0` may work to force installation of that specific version if you continue running into pip caching issues (on Python 3.8+).

**Comment by sutanAE** [comment] 2022-07-06 12:31
@brendan-ward seems like yes my end, sorry about that. Tried with Python 3.8 and installation works just fine. I missed reading the initial documentation. Now still trying to read some shapefilees but still failing because of gdal version from my anaconda installattion, still debuging the case.

**Comment by sutanAE** [comment] 2022-07-11 11:04
I'm back with python 3.8 and gdal 3.1.1. I'm using windows 11 with no administration privilege, and anaconda.

Installation, with no error:
```
(base) > conda create --name test-gdal
(base) > conda activate test-gdal
(test-gdal) > conda install -c conda-forge gdal=3.1.1
(test-gdal) > python -V
Python 3.8.13
(test-gdal) > conda list | grep gdal
# packages in environment at \.conda\envs\test-gdal:                                                                                                                                   gdal                      3.1.1            py38h3ba59e7_2    conda-forge                                                                                                                                  libgdal                   3.1.1                h98769a9_2    conda-forge

(test-gdal) > pip install --pre pyogrio
(test-gdal) > pip install pytest pandas pyproj shapely
(test-gdal) > pip install --no-deps geopandas
```

reading ```.shp``` with no error:
```
(test-gdal) > python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:45) [MSC v.1929 64 bit (AMD64)] on win32                                                                                         
Type "help", "copyright", "credits" or "license" for more information.                                                                                                                                    
>>> import pyogrio                                                                                                                                                                                        
>>> pyogrio.read_dataframe("test.shp")                                                                                                                                                                       

   field1   name       id                                           geometry                                                                                                                              
0      4      x      88025.0  LINESTRING (439227.827 110955.749, 439247.835 ...                                                                                                                              
1      4      x      87173.0  LINESTRING (430833.883 119926.692, 430884.813 ...                                                                                                                              
2      4      x      87175.0  LINESTRING (429978.613 122877.359, 429959.102 ...                                                                                                                              
3      4      x      87184.0  LINESTRING (429978.613 122877.359, 430000.709 ...                                                                                                                              
4      4      x      87219.0  LINESTRING (433308.737 113544.224, 433576.132 ... 
```

the ```pytest``` result

```
(test_gdal) > pytest --pyargs pyogrio >> test_result.csv
(test_gdal) > type test_result.csv
...
=========================== short test summary info ===========================
FAILED .conda/envs/test-gdal/lib/site-packages/pyogrio/tests/test_geopandas_io.py::test_write_dataframe_truly_mixed[.fgb]
FAILED .conda/envs/test-gdal/lib/site-packages/pyogrio/tests/test_geopandas_io.py::test_write_dataframe_truly_mixed[.geojson]
FAILED .conda/envs/test-gdal/lib/site-packages/pyogrio/tests/test_geopandas_io.py::test_write_dataframe_truly_mixed[.geojsonl]
FAILED .conda/envs/test-gdal/lib/site-packages/pyogrio/tests/test_geopandas_io.py::test_write_dataframe_truly_mixed[.gpkg]
FAILED .conda/envs/test-gdal/lib/site-packages/pyogrio/tests/test_geopandas_io.py::test_write_dataframe_truly_mixed_invalid
FAILED .conda/envs/test-gdal/lib/site-packages/pyogrio/tests/test_geopandas_io.py::test_custom_crs_io[.fgb]
FAILED .conda/envs/test-gdal/lib/site-packages/pyogrio/tests/test_geopandas_io.py::test_custom_crs_io[.geojson]
FAILED .conda/envs/test-gdal/lib/site-packages/pyogrio/tests/test_geopandas_io.py::test_custom_crs_io[.geojsonl]
FAILED .conda/envs/test-gdal/lib/site-packages/pyogrio/tests/test_geopandas_io.py::test_custom_crs_io[.gpkg]
FAILED .conda/envs/test-gdal/lib/site-packages/pyogrio/tests/test_geopandas_io.py::test_custom_crs_io[.shp]
=========== 10 failed, 260 passed, 12 skipped, 5 warnings in 21.60s ===========

```

**Comment by brendan-ward** [comment] 2022-07-11 19:32
@sutanAE you should install everything using conda, rather than GDAL via conda and everything else via pip; that may produce incompatibilities.  However, if you are just using conda for the base python environment and installing everything into it via pip, that may be OK; in that case you don't need to install GDAL because it is already bundled into the pyogrio 0.4.0 wheel on PyPI.  (you also don't need `--pre` for pyogrio as 0.4.0 is now available).

Unfortunately, I'm also not able to reproduce the failed tests using your setup instructions on macOS 10.15.  Can you please attach the output of `conda list`?  And also perhaps `pytest --pyargs pyogrio.tests.test_geopandas_io -v` might provide a little more detailed info for us to go on (just need to paste in the more detailed errors for the failing tests).

**Comment by brendan-ward** [comment] 2022-07-12 14:05
@sutanAE thanks for the extra info - that is helpful!  The tweet promoting this was when we only had pre-release wheels available and we wanted extra testing.  :)

For the record, I'm not specfically using `sudo` on macOS.  From your logs, it looks like that might not be the issue; it is writing test outputs to subdirectories within `C:/Users/SutanAE/AppData/Local/Temp/` which should be owned by your individual account and not run into permission issues.  Though I'm not a Windows user, so I can't say that for certain.

Instead, it looks like you are running into issues with shapely / GEOS writing the WKB version of geometries that we pass along to GDAL for writing to the output file:

```Python
self = <shapely.geos.WKBWriter object at 0x0000029AE36A03D0>
geom = <shapely.geometry.polygon.Polygon object at 0x0000029AE36A09A0>

    def write(self, geom):
        """Returns WKB byte string for geometry"""
        if geom is None or geom._geom is None:
            raise InvalidGeometryError("Null geometry supports no operations")
        size = c_size_t()
>       result = self._lgeos.GEOSWKBWriter_write(
            self._writer, geom._geom, pointer(size))
E       OSError: exception: access violation writing 0x0000029A00000000
```

From your dependency list, it looks like you have GEOS installed via conda-forge, and shapely installed via pip.  I _think_ that shapely wheels ship with GEOS built in, but perhaps on Windows there is a chance that the wrong GEOS dll is getting loaded (perhaps the one included with GDAL via conda-forge?  No idea...)

However, I'd still suggest using either conda OR pip but not a mix of both; that might be contributing to the issues here.  Since this issue is focused specifically on testing the new python wheels instead of conda, use pip all the way through.

Try creating your new environment using [virtualenv](https://docs.python.org/3/library/venv.html) or your tool of choice (pipenv, poetry, etc) or possibly an empty conda environment.  E.g.,

```
python -m venv c:\path\to\myenv
```

(see the link above for activation instructions for Windows)

```
c:\path\to\myenv\Scripts\activate.bat
```

Then 

```
pip install pyogrio shapely pygeos pytest pyproj pandas
pip install geopandas --no-deps
pytest --pyargs pyogrio.tests.test_geopandas_io -v
```

(note: I also suggest installing `pygeos` per the [requirements](https://github.com/geopandas/pyogrio#requirements))

If we're lucky, those tests will now pass!

**Comment by brendan-ward** [comment] 2023-01-06 03:36
Closing because wheels have now been generally tested for some time.

**Closed by brendan-ward** 2023-01-06 03:36 UTC
