### ISSUE TITLE
BUG: Cannot read with pyarrow when no non-geometry columns are loaded

### ISSUE THREAD

**Issue by joostmeulenbeld** [geopandas/pyogrio#212] opened 2023-01-20 09:55 UTC
When using `pyogrio.read_dataframe(..., use_arrow=True)`, reading a geopackage file fails if either the file has no non-geometry columns, or when supplying `columns=[]`.

This will raise the following error:
```
shapely.errors.GEOSException: ParseException: Unexpected EOF parsing WKB
```

Python script to show what raises an error and what doesn't:
```python
import geopandas as gpd
import pyogrio
from shapely import Point

# No error: when not using arrow
gpd.GeoDataFrame({"geometry": [Point(0, 0)]}, crs="EPSG:4326").to_file("point.gpkg", engine="pyogrio")
pyogrio.read_dataframe("point.gpkg", use_arrow=False)

# No error: if a non-geometry column is present
gpd.GeoDataFrame({"geometry": [Point(0, 0)], "field": [1]}, crs="EPSG:4326").to_file("point.gpkg", engine="pyogrio")
pyogrio.read_dataframe("point.gpkg", use_arrow=True)

# Error: not reading the non-geometry columns
gpd.GeoDataFrame({"geometry": [Point(0, 0)], "field": [1]}, crs="EPSG:4326").to_file("point.gpkg", engine="pyogrio")
pyogrio.read_dataframe("point.gpkg", use_arrow=True, columns=[])

# Error: file does not contain non-geometry columns
gpd.GeoDataFrame({"geometry": [Point(0, 0)]}, crs="EPSG:4326").to_file("point.gpkg", engine="pyogrio")
pyogrio.read_dataframe("point.gpkg", use_arrow=True)

# No error: when using FlatGeobuf instead of geopackage
gpd.GeoDataFrame({"geometry": [Point(0, 0)]}, crs="EPSG:4326").to_file("point.fgb", engine="pyogrio", driver="FlatGeobuf")
pyogrio.read_dataframe("point.fgb", use_arrow=True)
```

(This issue was also referenced in https://github.com/geopandas/pyogrio/issues/207#issuecomment-1397449905, but I thought it would be good to make a separate issue out of it)

## Environment
- Pop!_OS 22.04 LTS (linux kernel 6.0.12-76060006-generic)
- Python 3.10.8
- `pyogrio` 0.5.0 (from PyPI)
- `shapely` 2.0.0 (from PyPI)
- `geopandas` 0.12.2 (from PyPI)

**Comment by jorisvandenbossche** [comment] 2023-01-20 13:21
Thanks for narrowing it down to reading only geometries! 

cc @rouault given that we don't parse the features ourselves in case of using `OGR_L_GetArrowStream`, I _assume_ this might be a bug in GDAL?

Using this GeoPackage file with just one Point (download: [point.zip](https://github.com/geopandas/pyogrio/files/10466564/point.zip), zipped so I could upload it), created with:

```python
import geopandas
from shapely.geometry import Point
geopandas.GeoDataFrame({"geometry": [Point(0, 0)]}, crs="EPSG:4326").to_file("point.gpkg")
```


Reproducing this using the GDAL python bindings (installed from conda-forge, using latest GDAL 3.6.2):
```
In [1]: from osgeo import ogr

In [2]: dataset= ogr.Open("point.gpkg")

In [3]: layer = dataset.GetLayer()

In [4]: with layer.GetArrowStreamAsNumPy() as stream:
   ...:     print(list(stream))
   ...: 
[{'fid': array([1]), 'geom': array([b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
      dtype='|V21')}]

In [5]: with layer.GetArrowStreamAsNumPy(options=["INCLUDE_FID=NO"]) as stream:
   ...:     print(list(stream))
   ...: 
[{'geom': array([b''], dtype=object)}]
```

So here when the FIDs are included in the result (or in general any other attribute column), the geometry is fine, but if we are only reading geometries (no FIDs and no other attribute column), then the geometries becomes empty bytes.

**Comment by jorisvandenbossche** [comment] 2023-01-20 13:25
And it might be specific to the GPKG implementation of the arrow output. I don't see this with any of GeoJSON, Shapefile or FlatGeoBuf (but, Shapefile and FlatGeoBuf also seem to ignore the "INCLUDE_FID=NO" option, so can't check for sure since I can't get the "only geometry" case)

**Comment by rouault** [comment] 2023-01-20 14:24
> And it might be specific to the GPKG implementation of the arrow output.

fix in https://github.com/OSGeo/gdal/pull/7106

> Shapefile and FlatGeoBuf also seem to ignore the "INCLUDE_FID=NO" option

I can't reproduce this:
```
$ ogrinfo point.fgb -al -q

Layer name: point
OGRFeature(point):0
  POINT (0 0)

$ cat test.py

from osgeo import ogr
dataset= ogr.Open("point.fgb")
layer = dataset.GetLayer()
with layer.GetArrowStreamAsNumPy(options=["INCLUDE_FID=NO"]) as stream:
   print(list(stream))

$ python test.py

[{'wkb_geometry': array([b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'],
      dtype='|V21')}]
```

**Comment by jorisvandenbossche** [comment] 2023-01-20 14:36
Thanks for the quick fix!



> > Shapefile and FlatGeoBuf also seem to ignore the "INCLUDE_FID=NO" option
> 
> I can't reproduce this:

Sorry, I thought I created a FlatGeoBuf file, but it was actually a Shapefile in disguise ;) Indeed, with FlatGeoBuf I don't see the issue. And for the Shapefile, it seems I created a file with an actual FID column, so I have to check our own writing path then.

**Comment by theroggy** [comment] 2023-09-02 08:19
I think this can be closed? Or not?

**Comment by jorisvandenbossche** [comment] 2023-09-23 08:36
Yes, this is fixed on the GDAL side.

**Closed by jorisvandenbossche** 2023-09-23 08:36 UTC
